# ═══════════════════════════════════════════════════
# pages/02_🤖_Assistant_Gemma.py
# Module — Gemma Clinical Assistant
# ═══════════════════════════════════════════════════

import streamlit as st
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils.recommender import recommander, BACTERIES, PAYS, SITES
from utils.gemma_client import generer_explication_clinique

st.set_page_config(
    page_title="Gemma Assistant — ResistIA",
    page_icon="🤖",
    layout="wide"
)

# ═══════════════════════════════════════════════════
# LANGUAGE
# ═══════════════════════════════════════════════════

if "lang" not in st.session_state:
    st.session_state["lang"] = "English"

TEXT = {
    "Français": {
        "sidebar_desc": "Plateforme IA de Recommandation<br>Thérapeutique — Afrique de l'Ouest",
        "title": "🤖 Assistant Clinique Gemma",
        "subtitle": "*Gemma explique les recommandations générées par le moteur ResistIA, sans décider seul du traitement.*",
        "warning": "⚠️ <strong>Avertissement médical :</strong> ResistIA et Gemma sont des outils d’aide à la décision. Ils ne remplacent pas l’avis d’un professionnel de santé qualifié. Toute prescription doit être validée par un médecin.",
        "safety_title": "Principe de sécurité",
        "safety_text": "Le moteur ResistIA classe les antibiotiques à partir des données de résistance. Gemma intervient uniquement comme assistant d’explication complémentaire.",
        "profile": "📋 Profil clinique",
        "bacteria": "🦠 Bactérie identifiée",
        "country": "🌍 Pays",
        "site": "🧪 Site de prélèvement",
        "question": "Question clinique complémentaire",
        "placeholder": "Exemple : Le patient est allergique aux pénicillines. Quelle option privilégier ?",
        "button": "🧠 Générer la synthèse clinique",
        "spinner": "⚙️ Analyse ResistIA + commentaire Gemma en cours...",
        "no_data": "❌ Aucune donnée disponible pour cette bactérie.",
        "results": "🧬 Résultats",
        "table_title": "### 📋 Recommandations ResistIA",
        "table_cols": {
            "antibiotic": "Antibiotique",
            "efficacite_pct": "Efficacité (%)",
            "label": "Zone",
            "description": "Évaluation"
        },
        "summary_title": "### 🤖 Synthèse clinique contrôlée",
        "clinical_summary": "🧬 Résumé clinique",
        "recommended": "✅ Antibiotiques recommandés",
        "possible": "🟡 Options possibles",
        "prudence": "⚠️ À utiliser avec prudence",
        "avoid": "🚫 Antibiotiques à éviter",
        "justification": "🧠 Justification",
        "justification_text": "Le classement repose sur le pourcentage d’efficacité calculé par ResistIA. Les molécules avec une efficacité élevée sont privilégiées, tandis que celles associées à une résistance importante sont écartées.",
        "confidence": "📊 Niveau de confiance",
        "confidence_text": "Moyen à élevé, car la recommandation repose sur les données internes ResistIA. Les cas marqués “prudence” nécessitent une validation clinique renforcée.",
        "medical_warning": "⚠️ Avertissement médical",
        "medical_warning_text": "Ces résultats sont une aide à la décision. La prescription finale doit être validée par un professionnel de santé qualifié.",
        "gemma_comment": "🤖 Commentaire complémentaire généré par Gemma",
        "footer_info": "Gemma est utilisé ici comme moteur d’explication complémentaire. La recommandation fiable vient du moteur ResistIA.",
        "none": "Aucun"
    },

    "English": {
        "sidebar_desc": "AI-Powered Therapeutic<br>Recommendation Platform — West Africa",
        "title": "🤖 Gemma Clinical Assistant",
        "subtitle": "*Gemma explains recommendations generated by ResistIA without making treatment decisions itself.*",
        "warning": "⚠️ <strong>Medical disclaimer:</strong> ResistIA and Gemma are decision-support tools. They do not replace the opinion of a qualified healthcare professional. Any prescription must be validated by a physician.",
        "safety_title": "Safety principle",
        "safety_text": "The ResistIA engine ranks antibiotics using resistance data. Gemma acts only as a complementary explanation assistant.",
        "profile": "📋 Clinical profile",
        "bacteria": "🦠 Identified bacterium",
        "country": "🌍 Country",
        "site": "🧪 Specimen site",
        "question": "Additional clinical question",
        "placeholder": "Example: The patient is allergic to penicillins. Which option should be prioritized?",
        "button": "🧠 Generate clinical synthesis",
        "spinner": "⚙️ Running ResistIA + Gemma analysis...",
        "no_data": "❌ No data available for this bacterium.",
        "results": "🧬 Results",
        "table_title": "### 📋 ResistIA recommendations",
        "table_cols": {
            "antibiotic": "Antibiotic",
            "efficacite_pct": "Effectiveness (%)",
            "label": "Zone",
            "description": "Assessment"
        },
        "summary_title": "### 🤖 Controlled clinical synthesis",
        "clinical_summary": "🧬 Clinical summary",
        "recommended": "✅ Recommended antibiotics",
        "possible": "🟡 Possible options",
        "prudence": "⚠️ Use with caution",
        "avoid": "🚫 Antibiotics to avoid",
        "justification": "🧠 Justification",
        "justification_text": "The ranking is based on effectiveness percentages calculated by ResistIA. Molecules with high effectiveness are prioritized, while those associated with significant resistance are avoided.",
        "confidence": "📊 Confidence level",
        "confidence_text": "Moderate to high, since recommendations rely on ResistIA internal data. Cases marked as “caution” require stronger clinical validation.",
        "medical_warning": "⚠️ Medical warning",
        "medical_warning_text": "These results are intended as decision-support only. Final prescription must be validated by a qualified healthcare professional.",
        "gemma_comment": "🤖 Additional explanation generated by Gemma",
        "footer_info": "Gemma is used here as a complementary explanation engine. Reliable recommendation logic comes from ResistIA.",
        "none": "None"
    }
}

# ═══════════════════════════════════════════════════
# CSS
# ═══════════════════════════════════════════════════

st.markdown("""
<style>
[data-testid="stSidebar"] {
    background: linear-gradient(180deg, #1A5276 0%, #0B1F33 100%);
}

[data-testid="stSidebar"] * {
    color: white !important;
}

[data-testid="stSidebarNav"] > div:first-child {
    display: none;
}

[data-testid="stSidebarNav"] a:hover {
    background-color: rgba(255,255,255,0.10);
    border-radius: 8px;
    transition: all 0.25s ease;
}

h1, h2 {
    color: #1A5276 !important;
}

h3 {
    color: #1E8449 !important;
}

.logo-container {
    animation: fadeIn 1s ease-in-out;
    text-align: center;
}

@keyframes fadeIn {
    from { opacity: 0; transform: translateY(-8px); }
    to { opacity: 1; transform: translateY(0); }
}

.sidebar-desc {
    font-size: 0.8rem;
    color: #AED6F1;
    text-align: center;
    margin-top: 6px;
}

.avertissement {
    background: #FDEBD0;
    border-left: 5px solid #D35400;
    padding: 0.9rem 1.2rem;
    border-radius: 8px;
    margin-bottom: 1rem;
}

.info-card {
    background: #EBF5FB;
    border-left: 5px solid #1A5276;
    padding: 1rem 1.2rem;
    border-radius: 10px;
    margin-bottom: 1rem;
}

.synthese-card {
    background: #F8F9FA;
    border: 1px solid #DEE2E6;
    border-left: 5px solid #1E8449;
    border-radius: 12px;
    padding: 1.3rem 1.5rem;
    margin-top: 1rem;
    animation: fadeIn 0.8s ease-in-out;
}

.stButton > button {
    background-color: #1E8449;
    color: white;
    border-radius: 10px;
    border: none;
    padding: 0.65rem 2rem;
    font-weight: bold;
    font-size: 1rem;
    transition: all 0.25s ease;
}

.stButton > button:hover {
    background-color: #27AE60;
    transform: scale(1.02);
}

hr {
    border: none;
    height: 1px;
    background: #EAECEE;
}
</style>
""", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════
# SIDEBAR
# ═══════════════════════════════════════════════════

APP_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
logo_blanc = os.path.join(APP_DIR, "logo_resistia.png")

with st.sidebar:
    st.markdown("<div class='logo-container'>", unsafe_allow_html=True)

    if os.path.exists(logo_blanc):
        st.image(logo_blanc, width=200)

    st.markdown("</div>", unsafe_allow_html=True)

    st.session_state["lang"] = st.selectbox(
        "🌍 Language / Langue",
        options=["English", "Français"],
        index=0 if st.session_state["lang"] == "English" else 1
    )

    tx = TEXT[st.session_state["lang"]]

    st.markdown(
        f"<div class='sidebar-desc'>{tx['sidebar_desc']}</div>",
        unsafe_allow_html=True
    )

    st.markdown("<hr>", unsafe_allow_html=True)

# ═══════════════════════════════════════════════════
# PAGE
# ═══════════════════════════════════════════════════

tx = TEXT[st.session_state["lang"]]

st.title(tx["title"])
st.markdown(tx["subtitle"])

st.markdown(f"""
<div class="avertissement">
{tx["warning"]}
</div>
""", unsafe_allow_html=True)

st.markdown(f"""
<div class="info-card">
<strong>{tx["safety_title"]} :</strong><br>
{tx["safety_text"]}
</div>
""", unsafe_allow_html=True)

st.markdown("---")

# ── FORMULAIRE ───────────────────────────────────
st.subheader(tx["profile"])

col1, col2, col3 = st.columns(3)

with col1:
    bacterie = st.selectbox(tx["bacteria"], BACTERIES)

with col2:
    pays = st.selectbox(tx["country"], PAYS)

with col3:
    site = st.selectbox(tx["site"], SITES)

question = st.text_area(
    tx["question"],
    placeholder=tx["placeholder"],
    height=120
)

st.markdown("")

col_b1, col_b2, col_b3 = st.columns([1, 1, 1])
with col_b2:
    analyser = st.button(tx["button"], use_container_width=True)

# ── ANALYSE ──────────────────────────────────────
if analyser:
    with st.spinner(tx["spinner"]):
        resultat = recommander(bacterie, pays, site)

        if resultat is None:
            st.error(tx["no_data"])
        else:
            df = resultat["antibiotiques"]

            recommandes = df[df["label"].str.contains("RECOMMANDÉ", case=False, na=False)]
            possibles = df[df["label"].str.contains("POSSIBLE", case=False, na=False)]
            prudence = df[df["label"].str.contains("PRUDENCE", case=False, na=False)]
            eviter = df[df["label"].str.contains("ÉVITER|EVITER", case=False, na=False)]

            rec_list = ", ".join(recommandes["antibiotic"].tolist()) if not recommandes.empty else tx["none"]
            pos_list = ", ".join(possibles["antibiotic"].tolist()) if not possibles.empty else tx["none"]
            pru_list = ", ".join(prudence["antibiotic"].tolist()) if not prudence.empty else tx["none"]
            evit_list = ", ".join(eviter["antibiotic"].tolist()) if not eviter.empty else tx["none"]

            resume_recommandations = f"""
RECOMMENDED :
{recommandes[["antibiotic", "efficacite_pct"]].to_string(index=False)}

POSSIBLE :
{possibles[["antibiotic", "efficacite_pct"]].to_string(index=False)}

CAUTION :
{prudence[["antibiotic", "efficacite_pct"]].to_string(index=False)}

AVOID :
{eviter[["antibiotic", "efficacite_pct"]].to_string(index=False)}
"""

            contexte_question = ""
            if question.strip():
                contexte_question = f"\nClinical question : {question.strip()}"

            texte_pour_gemma = f"""
{resume_recommandations}

{contexte_question}
"""

            reponse = generer_explication_clinique(
                bacterie=bacterie,
                pays=pays,
                site=site,
                recommandations=texte_pour_gemma
            )

    st.markdown("---")
    st.subheader(f"{tx['results']} — *{bacterie}* | {pays} | {site}")

    st.markdown(tx["table_title"])

    table_df = df[["antibiotic", "efficacite_pct", "label", "description"]].copy()
    table_df = table_df.rename(columns=tx["table_cols"])

    st.dataframe(
        table_df,
        use_container_width=True,
        hide_index=True
    )

    st.markdown(tx["summary_title"])

    st.markdown(f"""
<div class="synthese-card">

<h4>{tx["clinical_summary"]}</h4>
For <strong>{bacterie}</strong> isolated from <strong>{site}</strong> in <strong>{pays}</strong>,
ResistIA estimates antibiotic effectiveness using available resistance profiles.

<h4>{tx["recommended"]}</h4>
{rec_list}

<h4>{tx["possible"]}</h4>
{pos_list}

<h4>{tx["prudence"]}</h4>
{pru_list}

<h4>{tx["avoid"]}</h4>
{evit_list}

<h4>{tx["justification"]}</h4>
{tx["justification_text"]}

<h4>{tx["confidence"]}</h4>
<strong>{tx["confidence_text"]}</strong>

<h4>{tx["medical_warning"]}</h4>
{tx["medical_warning_text"]}

</div>
""", unsafe_allow_html=True)

    with st.expander(tx["gemma_comment"]):
        st.markdown(reponse)

    st.info(tx["footer_info"])